### ISSUE TITLE
Hello World: angular2-compilers fails

### ISSUE THREAD

**Issue by robertohuertasm** [apollostack/angular2-apollo#84]
Hi, while trying to run the example in Windows 10 I've found issues with this package.
I've had to use `angular2-compilers@=0.6.0` to make it work.

**Comment by kamilkisiela** [comment]
I'm going to move Hello World example to be used with `angular-cli` instead of Meteor.

**Comment by robertohuertasm** [comment]
Ok, so the meteor example will be completely removed then?

**Comment by kamilkisiela** [comment]
This will be no longer a case after #88 will be merged.

About Meteor example. I don't want maitain Hello World example that is based Meteor because there are many developers that are not familiar with Meteor. In my opinion AngularCLI (with webpack or even just webpack without ng cli) fits into this really well.

You can also create your own repository with the demo based on Meteor, I would help you with it.
